### ISSUE TITLE
Porque não passar para o composer?

### ISSUE THREAD

**Issue by omarkdev** [valdiney/Ofir_Framework-0.1#2]
O que acha de passar o framework para composer e usar algumas outras dependencias de outras bibliotecas que poderiamos aplicar ali.

**Comment by valdiney** [comment]
Iai irmão beleza? Essa é uma tarefa que eu já pensei bastante! Porém quando eu escrevi esse Framework eu não tinha pensando em (names_space)... Ou seja, em uma forma de integrar isso com o (composer). Isso séria muito bom na verdade. Eu estou pensando em reescrever o projeto, porém dessa vez com olhos mais apurados.

**Comment by omarkdev** [comment]
Podemos reescrever todo o código, e separar por bibliotecas assim facilitando as atualizações.

Eu recentemente criei uma ferramenta para Code Igniter 3, aonde podemos criar controllers, models, helpers, rotas e views. Podemos implementar isso também no projeto.

**Comment by valdiney** [comment]
Meu caro, seria muito bom fazermos! Faz algum tempo que tento chamar pessoas para contribuírem, mas não obtive sucesso. Algumas acham básico de mais, outras complicado de mais. Pude aprender bastante durante o desenvolvimento dessa ferramenta. Toda a ajuda é bem vinda.

**Comment by conradoojr** [comment]
Eu topo ajudar!

**Comment by valdiney** [comment]
Opa! Massa!  Acho que a primeira coisa que poderíamos fazer é a inclusão das url amigáveis, pois é através delas que chamaríamos os Controllers e os Métodos. Ou seja, preparar as rotas.

**Comment by conradoojr** [comment]
Blz, vou baixar quando chegar em casa e dar uma olhada..
seria legal criarmos issue dos itens que ja sabemos que precisa melhorar/arrumar

**Comment by valdiney** [comment]
Isso mesmo! Na verdade trata-se de uma reescrita completa! kkkk É trabalhoso, mas compensa no final.

**Comment by conradoojr** [comment]
Sim, concordo. Temos que definir os passos para começarmos e ir aos poucos

**Comment by valdiney** [comment]
Bom, eu escrevi esse Framework só para aprender mais sobre a própria linguagem PHP, foi uma experiencia muito boa e hoje ele é usado para na composição de um sistema comercial que administra acessos de wifi via mikrotik. Sei que tem um monte de coisas que ferem o SOLID, mas resolvi da forma que eu pude. Sei que construir um Framework requer conhecimentos em engenharia de software... Mas vamos fazer como podermos! kkkk

**Comment by valdiney** [comment]
Só para termos uma ideia: 
1: url amigáveis, ou seja, rotas
2: load para o carregamento dos controllers 
3: Escolher a forma com que os Modelos serão inseridos nos Controllers. Se via injeção de dependências e acessados direto do construct dos controllers assim como no Laravel ou um método especifico para carregar os Controllers assim como no Codeigniter. 
Obs: No Ofir eu tentei sumular o Laravel e consegui obter os Modelos por via do construct dos Contrllers, mas para isso eu tive que recebe-los em um Array associativo. O lado negativo é que todos os Controllers estão sendo instanciados mesmos que não sejam chamados, ou seja, eles já estão lá prontos para semrem usados. 
4: Criação do Model base e como ele receberá a classe de conexão com o banco, ou criar uma outra camada para receber isso, no fim o model vai ter que receber isso de alguma forma.

**Comment by conradoojr** [comment]
Quanto ao load, posso estar falando besteira mas o composer ja não faz o autoload?
desse modo a gente só chama o model no controller usando o 'use'.
Desse modo daria certo?

**Comment by omarkdev** [comment]
O load que em quis dizer foi no caso do cor e igniter que podemos carregar um modal com `$this->model` no code igniter, ou com construct injection como no laravel. Eu acho que o uso do construct injection é mais limpo e gera mais liberdade. Ja o load do code igniter por mais q Vc consiga renomear sua dependência, Vc n consegue chamar duas dependências com o mesmo nome.

**Comment by omarkdev** [comment]
Acho interessante usarmos o padrão de código do laravel, ou do zend. Vocês tem alguma outra sugestão?

**Comment by valdiney** [comment]
Vou aprender bastante com vocês meus caros! kk Tenho que dá uma olhada melhor no lance do composer, nunca olhei de forma técnica para a forma com que ele faz o autoload. Mas fiquem a vontade para engrenar a coisa.  Sim,, acessar por via do construct é mágico.

**Comment by valdiney** [comment]
Quem quiser preparar essa forma ai do autoload com o composer só para dar uma luz. Manda bala!

**Comment by conradoojr** [comment]
Acho legal usarmos o mais proximo das PSR's. E ter um laravel como referencia acho ela menos complexo que o zend.

**Comment by valdiney** [comment]
E então jovens, as primeiras linhas vão sair de quem? kkk Esse final de semana vou tentar parar para pensar nas minhas primeiras contribuições.

**Comment by conradoojr** [comment]
Nem definimos um 'roteiro' ainda. Tipo o padrão que vamos seguir, qual framework vamos nos basear. Essas coisas..

**Comment by valdiney** [comment]
Verdade cara! Eu e minha pressa! Até que vendo outros frameworks, cada um vem com um intuito pessoal tirando claro o fato de suprir coisas básicas massivas durante o desenvolvimento. Tipo alguns pretende serem fullstack, outros, simples, leve....

**Comment by YamiHiei** [comment]
Adoraria contribuir também! 😄

**Comment by conradoojr** [comment]
Toda Ajuda é bem vinda!

**Comment by Paulo-ifce** [comment]
Olá gente, gostaria de contribuir para um projeto open source, mas ainda tenho o nível muito baixo, vocês podem me endicar materias, frameworks para estudar?

**Comment by valdiney** [comment]
Paulo-ifce o meu nível também não é tão alto. Mas isso vai aumentando de acordo com a quantidade de código que você escreve no seu dia a dia.  Atualmente estou trabalhando com o Laravel Framework e ele é bem legal. Dá uma olhada nele. Dá uma estudada em Orientação a objetos. E vai fazendo projetos para treinar.
