### ISSUE TITLE
Adicionar composer ao projeto

### ISSUE THREAD

**Issue by tadeubarbosa** [valdiney/Ofir_Framework-0.1#6]
Adicionar `composer` ao projeto facilitará bastante as coisas.
Vi no #2 (fechado), que isso já foi proposto um tempo atrás, talvez pudesse novamente ser iniciado.

Por exemplo, o projeto tem uma classe de upload de arquivos, mas esta classe poderia ser substituída pelo pacote [valdiney/TheUploadFiles](https://github.com/valdiney/TheUploadFiles). Facilitaria de mais a manutenção e contribuição de código.

**Comment by valdiney** [comment]
Na verdade eu só não adocionei o composer a este projeto porque já faz tempo que não dou nenhum commit nele! Ou seja, parei de contribuir! Mas esse framework já me ajudou bastante! hahah

**Comment by tadeubarbosa** [comment]
Haha!
Acho que poderia continuar a desenvolver a ideia, sei que tem muito framework no mercado, mas poderia(mos) usar este para aprendizado.

**Comment by valdiney** [comment]
Pow cara. Valeu pelas contribuições. Está ficando muito bacana as implementações!

**Comment by tadeubarbosa** [comment]
Talvez pudéssemos adicionar o `composer` e mandar alguns diretórios para dentro de `src/`, porque aí ficaria mais claro o que é interno e o que pode ser editado pelo desenvolvedor que for usar.

**Comment by tadeubarbosa** [comment]
Vou adicionando sugestões nas `issues`. Assim, a medida que alguém puder contribuir ficará a vontade.
